# fly.toml app configuration file generated for frosty-grass-5181 on 2023-09-04T22:35:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frosty-grass-5181"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3838
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
